[server]
headless = true
port = $PORT
enableCORS = false

[runner]
magicEnabled = false
watchDirectories = ["."]
watchFiles = []
watchIgnoreRegexes = [
    ".*fastcore.*",
    ".*torch.*",
    ".*fasttransform.*"
]
    